### ISSUE TITLE
Update Code to Cairo 2.6.X

### ISSUE THREAD

**Issue by caseywescott** [cienicera/nft-svg-onchain-multiseries#3]
Due to deprecated features in Cairo, we need to update the code to Cairo 2.6.X

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/nicera-labs).

### My background and how it can be leveraged
I'm a blockchain developer and I am up for the tax

### How I plan on tackling this issue
Please let me take this up, I'll deliver in no time.

**Comment by caseywescott** [comment]
This was solved by the pr:

https://github.com/cienicera/nft-svg-onchain-multiseries/pulls?q=is%3Apr+is%3Aclosed
